// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/cloud/account/account.proto

package accountconnect

import (
	account "codeberg.org/megakuul/cloudjam/pkg/api/v1/cloud/account"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountServiceName is the fully-qualified name of the AccountService service.
	AccountServiceName = "v1.cloud.account.AccountService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountServiceGetProcedure is the fully-qualified name of the AccountService's Get RPC.
	AccountServiceGetProcedure = "/v1.cloud.account.AccountService/Get"
	// AccountServiceListProcedure is the fully-qualified name of the AccountService's List RPC.
	AccountServiceListProcedure = "/v1.cloud.account.AccountService/List"
	// AccountServiceCreateProcedure is the fully-qualified name of the AccountService's Create RPC.
	AccountServiceCreateProcedure = "/v1.cloud.account.AccountService/Create"
	// AccountServiceUpdateProcedure is the fully-qualified name of the AccountService's Update RPC.
	AccountServiceUpdateProcedure = "/v1.cloud.account.AccountService/Update"
	// AccountServiceCredentialsProcedure is the fully-qualified name of the AccountService's
	// Credentials RPC.
	AccountServiceCredentialsProcedure = "/v1.cloud.account.AccountService/Credentials"
	// AccountServiceResetProcedure is the fully-qualified name of the AccountService's Reset RPC.
	AccountServiceResetProcedure = "/v1.cloud.account.AccountService/Reset"
	// AccountServiceFixProcedure is the fully-qualified name of the AccountService's Fix RPC.
	AccountServiceFixProcedure = "/v1.cloud.account.AccountService/Fix"
	// AccountServiceDeleteProcedure is the fully-qualified name of the AccountService's Delete RPC.
	AccountServiceDeleteProcedure = "/v1.cloud.account.AccountService/Delete"
)

// AccountServiceClient is a client for the v1.cloud.account.AccountService service.
type AccountServiceClient interface {
	// Get returns the accounts current state.
	Get(context.Context, *connect.Request[account.GetRequest]) (*connect.Response[account.GetResponse], error)
	// List returns a list of account states.
	List(context.Context, *connect.Request[account.ListRequest]) (*connect.Response[account.ListResponse], error)
	// Create creates a new cloudjam account and triggers the asynchron provisioning process on the provider.
	Create(context.Context, *connect.Request[account.CreateRequest]) (*connect.Response[account.CreateResponse], error)
	// Update updates teh cloudjam account metadata.
	Update(context.Context, *connect.Request[account.UpdateRequest]) (*connect.Response[account.UpdateResponse], error)
	// Credentials generates short lived credentials for the specified account (e.g. for maintenance).
	Credentials(context.Context, *connect.Request[account.CredentialsRequest]) (*connect.Response[account.CredentialsResponse], error)
	// Reset applies the nuke scripts to the account to clean it up and bring it back to ready state.
	Reset(context.Context, *connect.Request[account.ResetRequest]) (*connect.Response[account.ResetResponse], error)
	// Fix sets the account state forcefully to READY unbinds it from running Games.
	// This is very dangerous use with caution only if you actually fixed the account corruption.
	// Unfortunately this is required because *some* retarded providers (*AWS*) use account quotas
	// so we cannot just delete and create new accounts but must manually fix them when issues occur.
	Fix(context.Context, *connect.Request[account.FixRequest]) (*connect.Response[account.FixResponse], error)
	// Delete triggers the asynchron deletion process on the provider.
	// If called with *force* it will immediately remove cloudjam metadata (account will leak then!!!).
	Delete(context.Context, *connect.Request[account.DeleteRequest]) (*connect.Response[account.DeleteResponse], error)
}

// NewAccountServiceClient constructs a client for the v1.cloud.account.AccountService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accountServiceMethods := account.File_v1_cloud_account_account_proto.Services().ByName("AccountService").Methods()
	return &accountServiceClient{
		get: connect.NewClient[account.GetRequest, account.GetResponse](
			httpClient,
			baseURL+AccountServiceGetProcedure,
			connect.WithSchema(accountServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[account.ListRequest, account.ListResponse](
			httpClient,
			baseURL+AccountServiceListProcedure,
			connect.WithSchema(accountServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[account.CreateRequest, account.CreateResponse](
			httpClient,
			baseURL+AccountServiceCreateProcedure,
			connect.WithSchema(accountServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[account.UpdateRequest, account.UpdateResponse](
			httpClient,
			baseURL+AccountServiceUpdateProcedure,
			connect.WithSchema(accountServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		credentials: connect.NewClient[account.CredentialsRequest, account.CredentialsResponse](
			httpClient,
			baseURL+AccountServiceCredentialsProcedure,
			connect.WithSchema(accountServiceMethods.ByName("Credentials")),
			connect.WithClientOptions(opts...),
		),
		reset: connect.NewClient[account.ResetRequest, account.ResetResponse](
			httpClient,
			baseURL+AccountServiceResetProcedure,
			connect.WithSchema(accountServiceMethods.ByName("Reset")),
			connect.WithClientOptions(opts...),
		),
		fix: connect.NewClient[account.FixRequest, account.FixResponse](
			httpClient,
			baseURL+AccountServiceFixProcedure,
			connect.WithSchema(accountServiceMethods.ByName("Fix")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[account.DeleteRequest, account.DeleteResponse](
			httpClient,
			baseURL+AccountServiceDeleteProcedure,
			connect.WithSchema(accountServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountServiceClient implements AccountServiceClient.
type accountServiceClient struct {
	get         *connect.Client[account.GetRequest, account.GetResponse]
	list        *connect.Client[account.ListRequest, account.ListResponse]
	create      *connect.Client[account.CreateRequest, account.CreateResponse]
	update      *connect.Client[account.UpdateRequest, account.UpdateResponse]
	credentials *connect.Client[account.CredentialsRequest, account.CredentialsResponse]
	reset       *connect.Client[account.ResetRequest, account.ResetResponse]
	fix         *connect.Client[account.FixRequest, account.FixResponse]
	delete      *connect.Client[account.DeleteRequest, account.DeleteResponse]
}

// Get calls v1.cloud.account.AccountService.Get.
func (c *accountServiceClient) Get(ctx context.Context, req *connect.Request[account.GetRequest]) (*connect.Response[account.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// List calls v1.cloud.account.AccountService.List.
func (c *accountServiceClient) List(ctx context.Context, req *connect.Request[account.ListRequest]) (*connect.Response[account.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls v1.cloud.account.AccountService.Create.
func (c *accountServiceClient) Create(ctx context.Context, req *connect.Request[account.CreateRequest]) (*connect.Response[account.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls v1.cloud.account.AccountService.Update.
func (c *accountServiceClient) Update(ctx context.Context, req *connect.Request[account.UpdateRequest]) (*connect.Response[account.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Credentials calls v1.cloud.account.AccountService.Credentials.
func (c *accountServiceClient) Credentials(ctx context.Context, req *connect.Request[account.CredentialsRequest]) (*connect.Response[account.CredentialsResponse], error) {
	return c.credentials.CallUnary(ctx, req)
}

// Reset calls v1.cloud.account.AccountService.Reset.
func (c *accountServiceClient) Reset(ctx context.Context, req *connect.Request[account.ResetRequest]) (*connect.Response[account.ResetResponse], error) {
	return c.reset.CallUnary(ctx, req)
}

// Fix calls v1.cloud.account.AccountService.Fix.
func (c *accountServiceClient) Fix(ctx context.Context, req *connect.Request[account.FixRequest]) (*connect.Response[account.FixResponse], error) {
	return c.fix.CallUnary(ctx, req)
}

// Delete calls v1.cloud.account.AccountService.Delete.
func (c *accountServiceClient) Delete(ctx context.Context, req *connect.Request[account.DeleteRequest]) (*connect.Response[account.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// AccountServiceHandler is an implementation of the v1.cloud.account.AccountService service.
type AccountServiceHandler interface {
	// Get returns the accounts current state.
	Get(context.Context, *connect.Request[account.GetRequest]) (*connect.Response[account.GetResponse], error)
	// List returns a list of account states.
	List(context.Context, *connect.Request[account.ListRequest]) (*connect.Response[account.ListResponse], error)
	// Create creates a new cloudjam account and triggers the asynchron provisioning process on the provider.
	Create(context.Context, *connect.Request[account.CreateRequest]) (*connect.Response[account.CreateResponse], error)
	// Update updates teh cloudjam account metadata.
	Update(context.Context, *connect.Request[account.UpdateRequest]) (*connect.Response[account.UpdateResponse], error)
	// Credentials generates short lived credentials for the specified account (e.g. for maintenance).
	Credentials(context.Context, *connect.Request[account.CredentialsRequest]) (*connect.Response[account.CredentialsResponse], error)
	// Reset applies the nuke scripts to the account to clean it up and bring it back to ready state.
	Reset(context.Context, *connect.Request[account.ResetRequest]) (*connect.Response[account.ResetResponse], error)
	// Fix sets the account state forcefully to READY unbinds it from running Games.
	// This is very dangerous use with caution only if you actually fixed the account corruption.
	// Unfortunately this is required because *some* retarded providers (*AWS*) use account quotas
	// so we cannot just delete and create new accounts but must manually fix them when issues occur.
	Fix(context.Context, *connect.Request[account.FixRequest]) (*connect.Response[account.FixResponse], error)
	// Delete triggers the asynchron deletion process on the provider.
	// If called with *force* it will immediately remove cloudjam metadata (account will leak then!!!).
	Delete(context.Context, *connect.Request[account.DeleteRequest]) (*connect.Response[account.DeleteResponse], error)
}

// NewAccountServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountServiceHandler(svc AccountServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountServiceMethods := account.File_v1_cloud_account_account_proto.Services().ByName("AccountService").Methods()
	accountServiceGetHandler := connect.NewUnaryHandler(
		AccountServiceGetProcedure,
		svc.Get,
		connect.WithSchema(accountServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceListHandler := connect.NewUnaryHandler(
		AccountServiceListProcedure,
		svc.List,
		connect.WithSchema(accountServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceCreateHandler := connect.NewUnaryHandler(
		AccountServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(accountServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceUpdateHandler := connect.NewUnaryHandler(
		AccountServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(accountServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceCredentialsHandler := connect.NewUnaryHandler(
		AccountServiceCredentialsProcedure,
		svc.Credentials,
		connect.WithSchema(accountServiceMethods.ByName("Credentials")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceResetHandler := connect.NewUnaryHandler(
		AccountServiceResetProcedure,
		svc.Reset,
		connect.WithSchema(accountServiceMethods.ByName("Reset")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceFixHandler := connect.NewUnaryHandler(
		AccountServiceFixProcedure,
		svc.Fix,
		connect.WithSchema(accountServiceMethods.ByName("Fix")),
		connect.WithHandlerOptions(opts...),
	)
	accountServiceDeleteHandler := connect.NewUnaryHandler(
		AccountServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(accountServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/v1.cloud.account.AccountService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountServiceGetProcedure:
			accountServiceGetHandler.ServeHTTP(w, r)
		case AccountServiceListProcedure:
			accountServiceListHandler.ServeHTTP(w, r)
		case AccountServiceCreateProcedure:
			accountServiceCreateHandler.ServeHTTP(w, r)
		case AccountServiceUpdateProcedure:
			accountServiceUpdateHandler.ServeHTTP(w, r)
		case AccountServiceCredentialsProcedure:
			accountServiceCredentialsHandler.ServeHTTP(w, r)
		case AccountServiceResetProcedure:
			accountServiceResetHandler.ServeHTTP(w, r)
		case AccountServiceFixProcedure:
			accountServiceFixHandler.ServeHTTP(w, r)
		case AccountServiceDeleteProcedure:
			accountServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountServiceHandler struct{}

func (UnimplementedAccountServiceHandler) Get(context.Context, *connect.Request[account.GetRequest]) (*connect.Response[account.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.Get is not implemented"))
}

func (UnimplementedAccountServiceHandler) List(context.Context, *connect.Request[account.ListRequest]) (*connect.Response[account.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.List is not implemented"))
}

func (UnimplementedAccountServiceHandler) Create(context.Context, *connect.Request[account.CreateRequest]) (*connect.Response[account.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.Create is not implemented"))
}

func (UnimplementedAccountServiceHandler) Update(context.Context, *connect.Request[account.UpdateRequest]) (*connect.Response[account.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.Update is not implemented"))
}

func (UnimplementedAccountServiceHandler) Credentials(context.Context, *connect.Request[account.CredentialsRequest]) (*connect.Response[account.CredentialsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.Credentials is not implemented"))
}

func (UnimplementedAccountServiceHandler) Reset(context.Context, *connect.Request[account.ResetRequest]) (*connect.Response[account.ResetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.Reset is not implemented"))
}

func (UnimplementedAccountServiceHandler) Fix(context.Context, *connect.Request[account.FixRequest]) (*connect.Response[account.FixResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.Fix is not implemented"))
}

func (UnimplementedAccountServiceHandler) Delete(context.Context, *connect.Request[account.DeleteRequest]) (*connect.Response[account.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.cloud.account.AccountService.Delete is not implemented"))
}
