// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/cloud/definition/definition.proto (package v1.cloud.definition, syntax proto3)
/* eslint-disable */

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';
import { file_google_protobuf_timestamp } from '@bufbuild/protobuf/wkt';
import { file_buf_validate_validate } from '../../../buf/validate/validate_pb';
import type { CompressionMode, Definition } from '../definition_pb';
import { file_v1_cloud_definition } from '../definition_pb';

/**
 * Describes the file v1/cloud/definition/definition.proto.
 */
export const file_v1_cloud_definition_definition: GenFile =
	/*@__PURE__*/
	fileDesc(
		'CiR2MS9jbG91ZC9kZWZpbml0aW9uL2RlZmluaXRpb24ucHJvdG8SE3YxLmNsb3VkLmRlZmluaXRpb24iQQoKR2V0UmVxdWVzdBIdCgtwcm92aWRlcl9pZBgBIAEoCUIIukgFcgOwAQESFAoCaWQYAiABKAlCCLpIBXIDsAEBIjcKC0dldFJlc3BvbnNlEigKCmRlZmluaXRpb24YASABKAsyFC52MS5jbG91ZC5EZWZpbml0aW9uIlsKC0xpc3RSZXF1ZXN0Eh0KC3Byb3ZpZGVyX2lkGAEgASgJQgi6SAVyA7ABARIYCgVsaW1pdBgCIAEoBUIJukgGGgQYZCAAEhMKC3N0YXJ0X2FmdGVyGAMgASgJIjkKDExpc3RSZXNwb25zZRIpCgtkZWZpbml0aW9ucxgBIAMoCzIULnYxLmNsb3VkLkRlZmluaXRpb24ifwoNQ3JlYXRlUmVxdWVzdBIiCgRpbml0GAEgASgLMhQudjEuY2xvdWQuRGVmaW5pdGlvbhIuCgtjb21wcmVzc2lvbhgCIAEoDjIZLnYxLmNsb3VkLkNvbXByZXNzaW9uTW9kZRIaCgZiaW5hcnkYAyABKAxCCrpIB3oFGIDh6xciJgoOQ3JlYXRlUmVzcG9uc2USFAoCaWQYASABKAlCCLpIBXIDsAEBIn4KDVVwZGF0ZVJlcXVlc3QSIQoDbW9kGAEgASgLMhQudjEuY2xvdWQuRGVmaW5pdGlvbhIuCgtjb21wcmVzc2lvbhgCIAEoDjIZLnYxLmNsb3VkLkNvbXByZXNzaW9uTW9kZRIaCgZiaW5hcnkYAyABKAxCCrpIB3oFGIDh6xciEAoOVXBkYXRlUmVzcG9uc2UiRAoNRGVsZXRlUmVxdWVzdBIdCgtwcm92aWRlcl9pZBgBIAEoCUIIukgFcgOwAQESFAoCaWQYAiABKAlCCLpIBXIDsAEBIhAKDkRlbGV0ZVJlc3BvbnNlMqMDChFEZWZpbml0aW9uU2VydmljZRJICgNHZXQSHy52MS5jbG91ZC5kZWZpbml0aW9uLkdldFJlcXVlc3QaIC52MS5jbG91ZC5kZWZpbml0aW9uLkdldFJlc3BvbnNlEksKBExpc3QSIC52MS5jbG91ZC5kZWZpbml0aW9uLkxpc3RSZXF1ZXN0GiEudjEuY2xvdWQuZGVmaW5pdGlvbi5MaXN0UmVzcG9uc2USUQoGQ3JlYXRlEiIudjEuY2xvdWQuZGVmaW5pdGlvbi5DcmVhdGVSZXF1ZXN0GiMudjEuY2xvdWQuZGVmaW5pdGlvbi5DcmVhdGVSZXNwb25zZRJRCgZVcGRhdGUSIi52MS5jbG91ZC5kZWZpbml0aW9uLlVwZGF0ZVJlcXVlc3QaIy52MS5jbG91ZC5kZWZpbml0aW9uLlVwZGF0ZVJlc3BvbnNlElEKBkRlbGV0ZRIiLnYxLmNsb3VkLmRlZmluaXRpb24uRGVsZXRlUmVxdWVzdBojLnYxLmNsb3VkLmRlZmluaXRpb24uRGVsZXRlUmVzcG9uc2VCPFo6Y29kZWJlcmcub3JnL21lZ2FrdXVsL2Nsb3VkamFtL3BrZy9hcGkvdjEvY2xvdWQvZGVmaW5pdGlvbmIGcHJvdG8z',
		[file_buf_validate_validate, file_google_protobuf_timestamp, file_v1_cloud_definition]
	);

/**
 * @generated from message v1.cloud.definition.GetRequest
 */
export type GetRequest = Message<'v1.cloud.definition.GetRequest'> & {
	/**
	 * @generated from field: string provider_id = 1;
	 */
	providerId: string;

	/**
	 * @generated from field: string id = 2;
	 */
	id: string;
};

/**
 * Describes the message v1.cloud.definition.GetRequest.
 * Use `create(GetRequestSchema)` to create a new message.
 */
export const GetRequestSchema: GenMessage<GetRequest> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 0);

/**
 * @generated from message v1.cloud.definition.GetResponse
 */
export type GetResponse = Message<'v1.cloud.definition.GetResponse'> & {
	/**
	 * @generated from field: v1.cloud.Definition definition = 1;
	 */
	definition?: Definition;
};

/**
 * Describes the message v1.cloud.definition.GetResponse.
 * Use `create(GetResponseSchema)` to create a new message.
 */
export const GetResponseSchema: GenMessage<GetResponse> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 1);

/**
 * @generated from message v1.cloud.definition.ListRequest
 */
export type ListRequest = Message<'v1.cloud.definition.ListRequest'> & {
	/**
	 * @generated from field: string provider_id = 1;
	 */
	providerId: string;

	/**
	 * @generated from field: int32 limit = 2;
	 */
	limit: number;

	/**
	 * @generated from field: string start_after = 3;
	 */
	startAfter: string;
};

/**
 * Describes the message v1.cloud.definition.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 2);

/**
 * @generated from message v1.cloud.definition.ListResponse
 */
export type ListResponse = Message<'v1.cloud.definition.ListResponse'> & {
	/**
	 * @generated from field: repeated v1.cloud.Definition definitions = 1;
	 */
	definitions: Definition[];
};

/**
 * Describes the message v1.cloud.definition.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 3);

/**
 * @generated from message v1.cloud.definition.CreateRequest
 */
export type CreateRequest = Message<'v1.cloud.definition.CreateRequest'> & {
	/**
	 * @generated from field: v1.cloud.Definition init = 1;
	 */
	init?: Definition;

	/**
	 * @generated from field: v1.cloud.CompressionMode compression = 2;
	 */
	compression: CompressionMode;

	/**
	 * 50 MB
	 *
	 * @generated from field: bytes binary = 3;
	 */
	binary: Uint8Array;
};

/**
 * Describes the message v1.cloud.definition.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 4);

/**
 * @generated from message v1.cloud.definition.CreateResponse
 */
export type CreateResponse = Message<'v1.cloud.definition.CreateResponse'> & {
	/**
	 * @generated from field: string id = 1;
	 */
	id: string;
};

/**
 * Describes the message v1.cloud.definition.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 5);

/**
 * @generated from message v1.cloud.definition.UpdateRequest
 */
export type UpdateRequest = Message<'v1.cloud.definition.UpdateRequest'> & {
	/**
	 * @generated from field: v1.cloud.Definition mod = 1;
	 */
	mod?: Definition;

	/**
	 * @generated from field: v1.cloud.CompressionMode compression = 2;
	 */
	compression: CompressionMode;

	/**
	 * 50 MB
	 *
	 * @generated from field: bytes binary = 3;
	 */
	binary: Uint8Array;
};

/**
 * Describes the message v1.cloud.definition.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 6);

/**
 * @generated from message v1.cloud.definition.UpdateResponse
 */
export type UpdateResponse = Message<'v1.cloud.definition.UpdateResponse'> & {};

/**
 * Describes the message v1.cloud.definition.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 7);

/**
 * @generated from message v1.cloud.definition.DeleteRequest
 */
export type DeleteRequest = Message<'v1.cloud.definition.DeleteRequest'> & {
	/**
	 * @generated from field: string provider_id = 1;
	 */
	providerId: string;

	/**
	 * @generated from field: string id = 2;
	 */
	id: string;
};

/**
 * Describes the message v1.cloud.definition.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 8);

/**
 * @generated from message v1.cloud.definition.DeleteResponse
 */
export type DeleteResponse = Message<'v1.cloud.definition.DeleteResponse'> & {};

/**
 * Describes the message v1.cloud.definition.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> =
	/*@__PURE__*/
	messageDesc(file_v1_cloud_definition_definition, 9);

/**
 * @generated from service v1.cloud.definition.DefinitionService
 */
export const DefinitionService: GenService<{
	/**
	 * @generated from rpc v1.cloud.definition.DefinitionService.Get
	 */
	get: {
		methodKind: 'unary';
		input: typeof GetRequestSchema;
		output: typeof GetResponseSchema;
	};
	/**
	 * @generated from rpc v1.cloud.definition.DefinitionService.List
	 */
	list: {
		methodKind: 'unary';
		input: typeof ListRequestSchema;
		output: typeof ListResponseSchema;
	};
	/**
	 * @generated from rpc v1.cloud.definition.DefinitionService.Create
	 */
	create: {
		methodKind: 'unary';
		input: typeof CreateRequestSchema;
		output: typeof CreateResponseSchema;
	};
	/**
	 * @generated from rpc v1.cloud.definition.DefinitionService.Update
	 */
	update: {
		methodKind: 'unary';
		input: typeof UpdateRequestSchema;
		output: typeof UpdateResponseSchema;
	};
	/**
	 * @generated from rpc v1.cloud.definition.DefinitionService.Delete
	 */
	delete: {
		methodKind: 'unary';
		input: typeof DeleteRequestSchema;
		output: typeof DeleteResponseSchema;
	};
}> = /*@__PURE__*/ serviceDesc(file_v1_cloud_definition_definition, 0);
