syntax = "proto3";

package v1.cloud.account;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "v1/cloud/account.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/cloud/account";

message GetRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message GetResponse {
  Account account = 1;
}

message ListRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  int32 limit = 2 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
  string start_after = 3;
}

message ListResponse {
  repeated Account accounts = 1;
}

message CreateRequest {
  Account init = 1;
}

message CreateResponse {
  string id = 1 [(buf.validate.field).string = {uuid: true}];
}

message UpdateRequest {
  Account mod = 1;
}

message UpdateResponse {}

message CredentialsRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message CredentialsResponse {
  string credentials = 1;
}

message ResetRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message ResetResponse {}

message FixRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message FixResponse {}

message DeleteRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
  bool force = 3;
}

message DeleteResponse {}

service AccountService {
  // Get returns the accounts current state.
  rpc Get(GetRequest) returns (GetResponse);
  // List returns a list of account states.
  rpc List(ListRequest) returns (ListResponse);
  // Create creates a new cloudjam account and triggers the asynchron provisioning process on the provider.
  rpc Create(CreateRequest) returns (CreateResponse);
  // Update updates teh cloudjam account metadata.
  rpc Update(UpdateRequest) returns (UpdateResponse);
  // Credentials generates short lived credentials for the specified account (e.g. for maintenance).
  rpc Credentials(CredentialsRequest) returns (CredentialsResponse);
  // Reset applies the nuke scripts to the account to clean it up and bring it back to ready state.
  rpc Reset(ResetRequest) returns (ResetResponse);
  // Fix sets the account state forcefully to READY unbinds it from running Games.
  // This is very dangerous use with caution only if you actually fixed the account corruption.
  // Unfortunately this is required because *some* retarded providers (*AWS*) use account quotas
  // so we cannot just delete and create new accounts but must manually fix them when issues occur.
  rpc Fix(FixRequest) returns (FixResponse);
  // Delete triggers the asynchron deletion process on the provider.
  // If called with *force* it will immediately remove cloudjam metadata (account will leak then!!!).
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}
