// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/play/team.proto (package v1.play, syntax proto3)
/* eslint-disable */

import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2';
import { file_google_protobuf_timestamp } from '@bufbuild/protobuf/wkt';
import { file_buf_validate_validate } from '../../buf/validate/validate_pb';

/**
 * Describes the file v1/play/team.proto.
 */
export const file_v1_play_team: GenFile =
	/*@__PURE__*/
	fileDesc(
		'ChJ2MS9wbGF5L3RlYW0ucHJvdG8SB3YxLnBsYXkiSwoGUGxheWVyEhQKAmlkGAEgASgJQgi6SAVyA7ABARIOCgZwdWJfaWQYAiABKAkSGwoIdXNlcm5hbWUYAyABKAlCCbpIBnIEEAQYFCLcAQoEVGVhbRINCgVzY29wZRgBIAEoCRIZCgdnYW1lX2lkGAIgASgJQgi6SAVyA7ABARIUCgJpZBgDIAEoCUIIukgFcgOwAQESFwoEbmFtZRgEIAEoCUIJukgGcgQQAhhkEisKB3BsYXllcnMYBSADKAsyGi52MS5wbGF5LlRlYW0uUGxheWVyc0VudHJ5Eg0KBXNjb3JlGAYgASgBGj8KDFBsYXllcnNFbnRyeRILCgNrZXkYASABKAkSHgoFdmFsdWUYAiABKAsyDy52MS5wbGF5LlBsYXllcjoCOAFCMFouY29kZWJlcmcub3JnL21lZ2FrdXVsL2Nsb3VkamFtL3BrZy9hcGkvdjEvcGxheWIGcHJvdG8z',
		[file_buf_validate_validate, file_google_protobuf_timestamp]
	);

/**
 * @generated from message v1.play.Player
 */
export type Player = Message<'v1.play.Player'> & {
	/**
	 * @generated from field: string id = 1;
	 */
	id: string;

	/**
	 * @generated from field: string pub_id = 2;
	 */
	pubId: string;

	/**
	 * @generated from field: string username = 3;
	 */
	username: string;
};

/**
 * Describes the message v1.play.Player.
 * Use `create(PlayerSchema)` to create a new message.
 */
export const PlayerSchema: GenMessage<Player> = /*@__PURE__*/ messageDesc(file_v1_play_team, 0);

/**
 * @generated from message v1.play.Team
 */
export type Team = Message<'v1.play.Team'> & {
	/**
	 * @generated from field: string scope = 1;
	 */
	scope: string;

	/**
	 * @generated from field: string game_id = 2;
	 */
	gameId: string;

	/**
	 * @generated from field: string id = 3;
	 */
	id: string;

	/**
	 * @generated from field: string name = 4;
	 */
	name: string;

	/**
	 * @generated from field: map<string, v1.play.Player> players = 5;
	 */
	players: { [key: string]: Player };

	/**
	 * @generated from field: double score = 6;
	 */
	score: number;
};

/**
 * Describes the message v1.play.Team.
 * Use `create(TeamSchema)` to create a new message.
 */
export const TeamSchema: GenMessage<Team> = /*@__PURE__*/ messageDesc(file_v1_play_team, 1);
